### ISSUE TITLE
Unexpected failure while retrieving tokens.

### ISSUE THREAD

**Issue by 1liminal1** [alexa/alexa-avs-sample-app#516]
00:28:35.460 [Thread-16] ERROR com.amazon.alexa.avs.auth.AuthSetup - Failed to start companion service client
com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient$RemoteServiceException: TokenRetrievalFailure: Unexpected failure while retrieving tokens.

Hi guys.

ANy ideas?

Thanks

**Comment by Alexnagel** [comment]
Could you post the full output?

**Comment by 1liminal1** [comment]
pi@raspberrypi:~/Desktop/alexa-avs-sample-app/samples $ cd javaclient && mvn exec:exec
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.2
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
Created new window in existing browser session.
01:20:23.983 [Thread-16] ERROR com.amazon.alexa.avs.auth.AuthSetup - Failed to start companion service client
com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient$RemoteServiceException: TokenRetrievalFailure: Unexpected failure while retrieving tokens.
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.callService(CompanionServiceClient.java:229) ~[classes/:?]
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.getAccessToken(CompanionServiceClient.java:179) ~[classes/:?]
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.requestAccessToken(CompanionServiceAuthManager.java:99) ~[classes/:?]
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startNewProvisioningRequest(CompanionServiceAuthManager.java:69) ~[classes/:?]
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startRemoteProvisioning(CompanionServiceAuthManager.java:63) ~[classes/:?]
	at com.amazon.alexa.avs.auth.AuthSetup$2.run(AuthSetup.java:95) [classes/:?]

**Comment by 1liminal1** [comment]
Hows that?

**Comment by 1liminal1** [comment]
Other window says

Listening on port 3000
Successfully retrieved registration code for Lounge_Pi / 123456789
Error retrieving access token: TokenRetrievalFailure, Unexpected failure while retrieving tokens.

**Comment by 1liminal1** [comment]
I have seen someone say its an issue with the client secret. But I cant see any spaces or anything like that. Looks fine

**Comment by 1liminal1** [comment]
The only thing i did difference is put in the details using the notepad instead of nano. but it looks like it saved correctly and no spaces

**Comment by YOUN3SS** [comment]
I had also a problem yesterday to retrieve tokens, but I don't know if we had the same issue.
Check here https://github.com/alexa/alexa-avs-sample-app/issues/514

**Comment by 1liminal1** [comment]
Was it the same error?

What did you mean clean up your browser?

**Comment by Alexnagel** [comment]
Reading his issue, it seems it's not exact the same issue. With clean-up, cleaning cookies + cache was most likely meant. 

Just to be sure, 
- You set-up Alexa using the `automated_installer.sh`? 
- Check the `samples/companionService/config.js` to be correctly filled in. Specifically
    - clientId
    - clientSecret
* Check your security profile has been set up correctly (https://github.com/alexa/alexa-avs-sample-app/wiki/Create-Security-Profile)

**Comment by 1liminal1** [comment]
Hi there, 

Yes automated_installer.sh, with the client key ect, asked me if my info was correct, which it was. Checked the Security Profile, cant see any issues, as per the guide. Even created a new security profile from start to end and then put that into the config.js (not sure if I need to go though automated_install again, I thought not?) And still the same issue? Stumped!

**Comment by 1liminal1** [comment]
Ok, I fixed this, it wasnt happy using my DC for DNS (even though it was working for everything else). So once I put it to 8.8.8.8 worked fine. 

Thanks all

**Comment by alextestsf** [comment]
@1liminal1 - could you please tell me exactly what you changed and where as I am getting the same error message. It will really help me.

**Comment by 1liminal1** [comment]
So it seems, but I have no way to know for sure, that if you are running some kind of DNS country changer??? The code picks it up and wont allow you to get the tokens. 

But if you change the DNS settings on your Pi to 8.8.8.8 it will work. 

sudo nano /etc/resolv.conf

Then change the IP you see there to 8.8.8.8 (Google DNS)

Let me know if that works for you?

**Comment by alextestsf** [comment]
I changed the IP to 8.8.8.8 but still getting the following. Any direction will be helpful

I am getting the following error on the java client session:

"pi@raspberrypi:~ $ cd /home/pi/Desktop/alexa-avs-sample-app/samples/javaclient && mvn exec:exec
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.2
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---
14:56:27.979 [Thread-16] ERROR com.amazon.alexa.avs.auth.AuthSetup - Could not authenticate. Did you sign into Amazon before clicking ok?
14:56:27.982 [Thread-16] ERROR com.amazon.alexa.avs.auth.AuthSetup - Failed to start companion service client
com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient$RemoteServiceException: InvalidSessionId: No refresh tokens cached for session id: e0ade107-c22a-40f3-817d-1b5af4750271
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.callService(CompanionServiceClient.java:229) ~[classes/:?]
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceClient.getAccessToken(CompanionServiceClient.java:179) ~[classes/:?]
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.requestAccessToken(CompanionServiceAuthManager.java:99) ~[classes/:?]
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startNewProvisioningRequest(CompanionServiceAuthManager.java:69) ~[classes/:?]
	at com.amazon.alexa.avs.auth.companionservice.CompanionServiceAuthManager.startRemoteProvisioning(CompanionServiceAuthManager.java:63) ~[classes/:?]
	at com.amazon.alexa.avs.auth.AuthSetup$2.run(AuthSetup.java:95) [classes/:?]
[2021:2053:0207/145628:ERROR:cert_verify_proc_nss.cc(984)] CERT_PKIXVerifyCert for localhost failed err=-8179
[2178:2178:0207/145631:ERROR:sandbox_linux.cc(334)] InitializeSandbox() called with multiple threads in process gpu-process"

Also i see the following on the Companion Service session:

> alexa-voice-service-sample-companion-service@1.0.0 start /home/pi/Desktop/alexa-avs-sample-app/samples/companionService
> node ./bin/www

This node service needs to be running to store token information memory and vend them for the AVS app.

Listening on port 3000
Successfully retrieved registration code for my_device / 123456789
Error retrieving access token: InvalidSessionId, No refresh tokens cached for session id: e0ade107-c22a-40f3-817d-1b5af4750271

**Comment by Alexnagel** [comment]
Try removing the line containing `sessionId` from the config file at `samples/javaclient/config.json`. It should be at the bottom of the file and retry

**Comment by alextestsf** [comment]
I don't see any sessionId in the config.json file. 

Summarizing the scenario:
======================

on the Companion service terminal window:
================================
Able to start the companion service and it listens on port 3000.
It shows a message on the terminal "Successfully retrieved registration code for my_device / 123456789

on the java client terminal window:
============================

i fire: mvn exec:exec and the output on the window is:

Scanning for projects 
[INFO]
.
.
.
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ----

Alexa Voice Service (Java applet kind of window opens)
========================================
Login to Register/Authenticate your Device

There is a url like below and when i copy and paste this url in a browser or directly open on a default browser it takes me to a Amazon error page.

https://localhost:3000/provision/a3dd5dbbfdfb7c4bde7262bf6


I am not sure what is going here as it is not authorizing me and i don't the know reason. Please help.

**Comment by alextestsf** [comment]
Now it takes me the sign into Alexa using your Amazon account and prompts to enter username and password which passes through successfully.

It then takes me to a page where it reads: when you click "okay" you also accept All Amazon terms found here. Here I click okay and I get a message stating: 

We are sorry! An error occurred when we tried to process your request. Rest assured we are already working on the problem and expect to resolve it shortly.

I am not sure if any of you have seen this message. Let me know if you have any ideas.

**Comment by Alexnagel** [comment]
@alextestsf Check #5 if some of those solutions may help you

**Comment by alextestsf** [comment]
@Alexnagel - Everything worked fine and your direction to refer #5 was very helpful.
Thank you all.

**Comment by rjsuzuki** [comment]
In case anyone is getting the 400 error during the authentication/registration process, please check this tutorial --> https://github.com/alexa/alexa-avs-sample-app/wiki/Create-Security-Profile

In my case, I didn't setup the security profile correctly. I didn't configure the "Allowed Origins" and "Allowed Return URLs" in the "Web Settings" tab. Once I did that, everything worked fine.

**Comment by thedroidbuilder** [comment]
Okay, what else do i check?  I still get 400 errors after doing all of this.  How can I troubleshoot this further?  Can we share an account from Amazon that we know works so I can compare what is wrong with mine.  I'm getting a little frustrated trying to figure this out.

**Comment by rjsuzuki** [comment]
If your setup is the same as the tutorial from my previous post, I would then check your code. Make sure you put your auth credentials in the proper spots.

**Comment by thedroidbuilder** [comment]
Yep, currently I'm now troubleshooting the following...
ERROR:Failed to open PortAudio stream.Device unavailable
ERROR:KittAiSnowboyWakeWordEngine: Initialization error:Failed to open PortAudio stream.
ERROR:WakeWordAgent: exception in constructor: Failed to open PortAudio stream.
ERROR:main: Exception happened: Failed to open PortAudio stream.
INFO:Shutting down Wake Word Agent


I'll play with trying to fix this first and come back to my problem above if it persists.
Thanks

**Comment by howlr5** [comment]
I am getting Error: Url must be between 1 and 2000 characters??? when I try and set allowed origin to https://localhost:3000

**Comment by yp7y-stu** [comment]
I've had same trouble. But I can get one solution.
My cause of failure is to type/click rashly.
First of all, type the command 'npm start' on the first terminal and then you'll see "Listening on port 3000". Secondary, type the command 'mvn exec:exec' on other terminal and then following message and pop-up "Alexa Voice Service-V2016****" window with Login to Register/Authenticate your Device.
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Alexa Voice Service Sample Java Client 20160207.8
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ sample-java-client ---

So, you'll click 'yes' on the "Login to Register/Authenticate your Device" window. 

The Point is to WAIT for the procedure output step by step. WAIT for opening the Amazon sign in on the browser, and then sign in.
And so you can see device tokens ready on localhost:3000 browser. next, click the 'OK' on "Login to Register/Authenticate your Device".
Finally, you can see "Successfully retrieved access token for session id: 205f6eb5-496f-***************aac" instead of "Error retrieving access token: InvalidSessionId, No refresh tokens cached for session id: e0ade107-c22a-40f*********"

I wish this issue would be resolved by this comment.

**Comment by ueabu** [comment]
I was having the same error and I looked in the config.js file in samples/companion service/config.js and I saw that I was off on the client secret ID by one letter, fixed that and it worked
